### ISSUE TITLE
Add author name to each article card

### ISSUE THREAD

**Issue by asessums7** [ArberTu474/Visit-Dibra-website#112]
# Tasks

- [x] Add the author icon and name in `ArticleCard`
- [x] update each article to have an author property
- [x] Maybe add a profile icon for the author and move the date
- [x] Create a [author] slug page

**Comment by asessums7** [comment]
Add author name under or above the date, visible on each card.
