### ISSUE TITLE
Add a dedicated div for the `Visit Diber Guide`

### ISSUE THREAD

**Issue by ArberTu474** [ArberTu474/Visit-Dibra-website#124]
# Tasks:

- [x] Create the design
- [x] Mobile view 
- [x] Desktop view
- [x] Has the proper content
- [x] Make the guides downloadable
