### ISSUE TITLE
fix some bugs in the `/stays` page

### ISSUE THREAD

**Issue by ArberTu474** [ArberTu474/Visit-Dibra-website#147]
# Tasks

- [ ] Add a list of locations 
- [x] Add a list accommodation types
- [x] Fix the layout in mobile view 
- [x] Add a `Nothing was Found` prompt 
- [x] make the search box sticky 
- [x] Add an icon for the accommodation type
