### ISSUE TITLE
Create website components

### ISSUE THREAD

**Issue by ArberTu474** [ArberTu474/Visit-Dibra-website#17]
# Tasks:

- Button
    - [x] Icon button 
    - [x] Add pill shape button
    - [x] Add multi color support
 
- NavBar
    - [x] Mobile view 
    - [x] Desktop view
    - [x] Has the proper content

- Card
    - [x] Full image in a card
    - [x] Add/ Remove the padding of the card

-  Footer
    - [x] Mobile view 
    - [x] Desktop view
    - [x] Has the proper content
