### ISSUE TITLE
Add semantic HTML tags

### ISSUE THREAD

**Issue by ArberTu474** [ArberTu474/Visit-Dibra-website#179]
### [Reference](https://www.w3schools.com/html/html5_semantic_elements.asp)

# Tasks

- [x] Wrap the navbar with a `<nav>` tag
- [x] Warp the footer with a `<footer>` tag
- [x] Wrap the heading with `<header>` tag
- [x] Replace `<div>` tags with `<section>` tags
- [x] Add `<aside>` tags in the article layout and search boxes
