### ISSUE TITLE
Create the full destination map with its locations

### ISSUE THREAD

**Issue by ArberTu474** [ArberTu474/Visit-Dibra-website#18]
# Tasks:

- [ ] Identify the touristic locations
- [ ] Generate the new `svg`  map
- [x] Make the map interactive
