### ISSUE TITLE
Create a `svg` logo for the website

### ISSUE THREAD

**Issue by ArberTu474** [ArberTu474/Visit-Dibra-website#19]
# Tasks:

- [x] Create a `svg` logo of Visit Diber for the website
- [x] Create the `favicon` of the website
- [x] Use the the new icon in the website
