### ISSUE TITLE
Add the `FAQ Section`

### ISSUE THREAD

**Issue by ArberTu474** [ArberTu474/Visit-Dibra-website#44]
### Tasks:

- [ ] Mobile view 
- [ ] Desktop view
- [ ] Has the proper content
- [ ] Has the proper images 
- [ ] Has the proper links
