### ISSUE TITLE
Add the `Activities Section`

### ISSUE THREAD

**Issue by ArberTu474** [ArberTu474/Visit-Dibra-website#7]
### Tasks:

- [x] Mobile view 
- [x] Desktop view
- [x] Display new activities 
- [ ] Has the proper content
- [ ] Has the proper images
