### ISSUE TITLE
Add the `Maps` page

### ISSUE THREAD

**Issue by ArberTu474** [ArberTu474/Visit-Dibra-website#83]
#Tasks:

- [x] Mobile view 
- [x] Desktop view
- [ ] Upload the pdf maps
- [x] Make the pdf-s downloadable
- [ ] Has the proper images
